# Generated by Django 4.2.8 on 2024-01-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
    ]
