# Generated by Django 4.2.8 on 2024-01-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_remove_place_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='job',
        ),
    ]
